// -----------------------------------------------------------------------------
//  MD - 跨平台 Markdown 阅读器
//  文件：Services/BuiltinThemes.cs
//  说明：内置主题。为保证「单 exe 自包含」，主题不放在 .json 资源文件里，
//        而是以 JSON 文本常量内嵌（可直接复制到 <配置目录>/themes/ 下改）。
//
//        主题采用「模板 + 差异覆盖」机制：
//          · 亮色主题以 LightTemplate 为底，暗色主题以 DarkTemplate 为底
//          · 主题文件/定义中只需写想改的字段，未写的自动继承模板
//          · 因此下面每套主题都很短，而 typography 也可以只调行高/字号
//
//        字段含义见 Models/ThemeDefinition.cs 的注释。
//  作者：MD
//  创建：2026-09-21
//  修改：2026-09-21  初版
// -----------------------------------------------------------------------------

namespace MD.Services;

internal static class BuiltinThemes
{
    /// <summary>亮色模板（同时作为 github-light 主题本体）。</summary>
    public const string LightTemplate = """
    {
      "colors": {
        "windowBg": "#FFFFFFFF",
        "toolbarBg": "#FFF6F8FA",
        "toolbarBorder": "#FFD8DEE4",
        "toolbarText": "#FF57606A",
        "toolbarTextHover": "#FF0969DA",
        "accent": "#FF0969DA",
        "sidebarBg": "#FFF6F8FA",
        "sidebarBorder": "#FFE1E4E8",
        "sidebarText": "#FF57606A",
        "sidebarTextActive": "#FF0969DA",
        "sidebarHoverBg": "#FFEAEEF2",
        "statusBarBg": "#FFF6F8FA",
        "statusBarText": "#FF8B949E",
        "scrim": "#66000000",
        "panelBg": "#FFFFFFFF",
        "panelBorder": "#FFD0D7DE",
        "controlBg": "#FFFFFFFF",
        "controlBorder": "#FFD0D7DE",
        "editorBg": "#FFFFFFFF",
        "text": "#FF1F2328",
        "textSecondary": "#FF59636E",
        "heading": "#FF1F2328",
        "headingBorder": "#FFE8EBEF",
        "link": "#FF0969DA",
        "rule": "#FFD8DEE4",
        "selection": "#FFB6DBFF",
        "inlineCodeText": "#FFCF222E",
        "codeBg": "#FFF6F8FA",
        "codeBorder": "#FFD0D7DE",
        "codeText": "#FF1F2328",
        "codeHeaderText": "#FF8B949E",
        "quoteBg": "#00000000",
        "quoteText": "#FF59636E",
        "quoteBorder": "#FFD0D7DE",
        "tableBorder": "#FFD0D7DE",
        "tableHeaderBg": "#FFF6F8FA",
        "tableHeaderText": "#FF1F2328",
        "tableStripeBg": "#00000000",
        "syntaxKeyword": "#FFCF222E",
        "syntaxType": "#FF953800",
        "syntaxString": "#FF0A3069",
        "syntaxNumber": "#FF0550AE",
        "syntaxComment": "#FF6E7781",
        "syntaxFunction": "#FF8250DF",
        "syntaxOperator": "#FF0550AE",
        "syntaxPunctuation": "#FF59636E",
        "syntaxVariable": "#FF1F2328",
        "syntaxBuiltin": "#FF0550AE"
      }
    }
    """;

    /// <summary>暗色模板（同时作为 github-dark 主题本体）。</summary>
    public const string DarkTemplate = """
    {
      "colors": {
        "windowBg": "#FF0D1117",
        "toolbarBg": "#FF161B22",
        "toolbarBorder": "#FF30363D",
        "toolbarText": "#FF9198A1",
        "toolbarTextHover": "#FF4493F8",
        "accent": "#FF4493F8",
        "sidebarBg": "#FF0D1117",
        "sidebarBorder": "#FF30363D",
        "sidebarText": "#FF9198A1",
        "sidebarTextActive": "#FF4493F8",
        "sidebarHoverBg": "#FF1F262E",
        "statusBarBg": "#FF161B22",
        "statusBarText": "#FF6E7681",
        "scrim": "#99000000",
        "panelBg": "#FF161B22",
        "panelBorder": "#FF30363D",
        "controlBg": "#FF0D1117",
        "controlBorder": "#FF30363D",
        "editorBg": "#FF0D1117",
        "text": "#FFE6EDF3",
        "textSecondary": "#FF9198A1",
        "heading": "#FFF0F6FC",
        "headingBorder": "#FF21262D",
        "link": "#FF4493F8",
        "rule": "#FF30363D",
        "selection": "#FF1F6FEB66",
        "inlineCodeText": "#FFFF7B72",
        "codeBg": "#FF161B22",
        "codeBorder": "#FF30363D",
        "codeText": "#FFE6EDF3",
        "codeHeaderText": "#FF6E7681",
        "quoteBg": "#00000000",
        "quoteText": "#FF9198A1",
        "quoteBorder": "#FF3D444D",
        "tableBorder": "#FF30363D",
        "tableHeaderBg": "#FF161B22",
        "tableHeaderText": "#FFF0F6FC",
        "tableStripeBg": "#0DFFFFFF",
        "syntaxKeyword": "#FFFF7B72",
        "syntaxType": "#FFFFA657",
        "syntaxString": "#FFA5D6FF",
        "syntaxNumber": "#FF79C0FF",
        "syntaxComment": "#FF8B949E",
        "syntaxFunction": "#FFD2A8FF",
        "syntaxOperator": "#FF79C0FF",
        "syntaxPunctuation": "#FF9198A1",
        "syntaxVariable": "#FFE6EDF3",
        "syntaxBuiltin": "#FF79C0FF"
      }
    }
    """;

    /// <summary>内置主题清单（只写与模板的差异）。</summary>
    public const string Definitions = """
    [
      {
        "id": "github-light",
        "name": "GitHub 亮色",
        "author": "内置",
        "isDark": false,
        "typography": { "baseFontSize": 16.5, "lineHeight": 1.75, "contentMaxWidth": 820 }
      },
      {
        "id": "whitey",
        "name": "Whitey 极简白",
        "author": "内置",
        "isDark": false,
        "colors": {
          "toolbarBg": "#FFFFFFFF",
          "toolbarBorder": "#FFEBEBEB",
          "toolbarText": "#FF8A8A8A",
          "toolbarTextHover": "#FF2E7DAF",
          "accent": "#FF2E7DAF",
          "sidebarBg": "#FFFFFFFF",
          "sidebarBorder": "#FFEDEDED",
          "sidebarText": "#FF8A8A8A",
          "sidebarTextActive": "#FF2E7DAF",
          "sidebarHoverBg": "#FFF4F7FA",
          "statusBarBg": "#FFFFFFFF",
          "statusBarText": "#FFB0B0B0",
          "text": "#FF333333",
          "textSecondary": "#FF808080",
          "heading": "#FF111111",
          "headingBorder": "#FFF0F0F0",
          "link": "#FF2E7DAF",
          "rule": "#FFEAEAEA",
          "inlineCodeText": "#FFC7254E",
          "codeBg": "#FFF8F8F8",
          "codeBorder": "#FFEDEDED",
          "codeText": "#FF333333",
          "quoteText": "#FF8A8A8A",
          "quoteBorder": "#FFE0E0E0",
          "tableBorder": "#FFE6E6E6",
          "tableHeaderBg": "#FFFAFAFA",
          "tableHeaderText": "#FF111111",
          "syntaxKeyword": "#FF9B2A6B",
          "syntaxString": "#FF2E7D32",
          "syntaxComment": "#FFAAAAAA",
          "syntaxNumber": "#FF1565C0",
          "syntaxType": "#FFB26A00",
          "syntaxFunction": "#FF6A3FBF"
        },
        "typography": { "baseFontSize": 16.5, "lineHeight": 1.8, "contentMaxWidth": 760, "paragraphSpacing": 0.85 }
      },
      {
        "id": "pixyll",
        "name": "Pixyll 留白",
        "author": "内置",
        "isDark": false,
        "colors": {
          "toolbarBg": "#FFFFFFFF",
          "toolbarBorder": "#FFF1F1F1",
          "toolbarText": "#FF9A9A9A",
          "toolbarTextHover": "#FF3A7CA5",
          "accent": "#FF3A7CA5",
          "sidebarBg": "#FFFFFFFF",
          "sidebarBorder": "#FFF0F0F0",
          "sidebarText": "#FF9A9A9A",
          "sidebarTextActive": "#FF3A7CA5",
          "sidebarHoverBg": "#FFF6F9FB",
          "statusBarBg": "#FFFFFFFF",
          "statusBarText": "#FFB8B8B8",
          "text": "#FF404040",
          "textSecondary": "#FF8C8C8C",
          "heading": "#FF1F1F1F",
          "headingBorder": "#FFF4F4F4",
          "link": "#FF3A7CA5",
          "rule": "#FFEEEEEE",
          "inlineCodeText": "#FFB4444B",
          "codeBg": "#FFF9F9F9",
          "codeBorder": "#FFF0F0F0",
          "quoteText": "#FF8C8C8C",
          "quoteBorder": "#FFDCDCDC",
          "tableBorder": "#FFEBEBEB",
          "tableHeaderBg": "#FFFBFBFB",
          "syntaxKeyword": "#FFA13D63",
          "syntaxString": "#FF3B7A57",
          "syntaxComment": "#FFB0B0B0",
          "syntaxNumber": "#FF1F6F9E",
          "syntaxType": "#FFB0713A",
          "syntaxFunction": "#FF6F4FB0"
        },
        "typography": { "baseFontSize": 17, "lineHeight": 1.85, "contentMaxWidth": 720, "contentPadding": 40, "paragraphSpacing": 0.95, "headingMarginTop": 2.0 }
      },
      {
        "id": "newsprint",
        "name": "Newsprint 新闻纸",
        "author": "内置",
        "isDark": false,
        "colors": {
          "windowBg": "#FFFCFAF6",
          "toolbarBg": "#FFF6F2EA",
          "toolbarBorder": "#FFE4DCCE",
          "toolbarText": "#FF7A7368",
          "toolbarTextHover": "#FF3B6E9E",
          "accent": "#FF3B6E9E",
          "sidebarBg": "#FFF8F5EF",
          "sidebarBorder": "#FFE4DCCE",
          "sidebarText": "#FF7A7368",
          "sidebarTextActive": "#FF3B6E9E",
          "sidebarHoverBg": "#FFEFE9DE",
          "statusBarBg": "#FFF6F2EA",
          "statusBarText": "#FFA79E8E",
          "panelBg": "#FFFCFAF6",
          "controlBg": "#FFFCFAF6",
          "controlBorder": "#FFDCD3C3",
          "editorBg": "#FFFCFAF6",
          "text": "#FF2B2A27",
          "textSecondary": "#FF6F6A61",
          "heading": "#FF171614",
          "headingBorder": "#FFE7E0D3",
          "link": "#FF3B6E9E",
          "rule": "#FFE2DACA",
          "inlineCodeText": "#FFA5413C",
          "codeBg": "#FFF4F0E7",
          "codeBorder": "#FFE4DCCE",
          "codeText": "#FF2B2A27",
          "codeHeaderText": "#FFA79E8E",
          "quoteText": "#FF6F6A61",
          "quoteBorder": "#FFD8CEBB",
          "tableBorder": "#FFE0D8C8",
          "tableHeaderBg": "#FFF4F0E7",
          "tableHeaderText": "#FF171614",
          "syntaxKeyword": "#FF9C3B36",
          "syntaxString": "#FF4A6B3E",
          "syntaxComment": "#FFA79E8E",
          "syntaxNumber": "#FF2F5F86",
          "syntaxType": "#FF9A6A2E",
          "syntaxFunction": "#FF6B4A8A"
        },
        "typography": {
          "baseFontSize": 17.5,
          "lineHeight": 1.95,
          "contentMaxWidth": 740,
          "contentPadding": 36,
          "paragraphSpacing": 1.0,
          "headingMarginTop": 2.1,
          "fontFamily": "Georgia"
        }
      },
      {
        "id": "solarized-light",
        "name": "Solarized 日光",
        "author": "内置",
        "isDark": false,
        "colors": {
          "windowBg": "#FFFDF6E3",
          "toolbarBg": "#FFEEE8D5",
          "toolbarBorder": "#FFDDD6C1",
          "toolbarText": "#FF7A8B8D",
          "toolbarTextHover": "#FF268BD2",
          "accent": "#FF268BD2",
          "sidebarBg": "#FFEEE8D5",
          "sidebarBorder": "#FFDDD6C1",
          "sidebarText": "#FF657B83",
          "sidebarTextActive": "#FF268BD2",
          "sidebarHoverBg": "#FFE4DDC8",
          "statusBarBg": "#FFEEE8D5",
          "statusBarText": "#FF93A1A1",
          "panelBg": "#FFFDF6E3",
          "controlBg": "#FFFDF6E3",
          "controlBorder": "#FFDDD6C1",
          "editorBg": "#FFFDF6E3",
          "text": "#FF586E75",
          "textSecondary": "#FF839496",
          "heading": "#FF073642",
          "headingBorder": "#FFE7E0CC",
          "link": "#FF268BD2",
          "rule": "#FFE3DCC8",
          "inlineCodeText": "#FFCB4B16",
          "codeBg": "#FFEEE8D5",
          "codeBorder": "#FFDDD6C1",
          "codeText": "#FF586E75",
          "codeHeaderText": "#FF93A1A1",
          "quoteText": "#FF839496",
          "quoteBorder": "#FFD7D0BB",
          "tableBorder": "#FFDDD6C1",
          "tableHeaderBg": "#FFEEE8D5",
          "tableHeaderText": "#FF073642",
          "syntaxKeyword": "#FF859900",
          "syntaxString": "#FF2AA198",
          "syntaxComment": "#FF93A1A1",
          "syntaxNumber": "#FFD33682",
          "syntaxType": "#FFB58900",
          "syntaxFunction": "#FF268BD2"
        },
        "typography": { "baseFontSize": 16.5, "lineHeight": 1.8, "contentMaxWidth": 800 }
      },
      {
        "id": "github-dark",
        "name": "GitHub 暗色",
        "author": "内置",
        "isDark": true,
        "typography": { "baseFontSize": 16.5, "lineHeight": 1.75, "contentMaxWidth": 820 }
      },
      {
        "id": "night",
        "name": "Night 深夜",
        "author": "内置",
        "isDark": true,
        "colors": {
          "windowBg": "#FF2B3035",
          "toolbarBg": "#FF262B30",
          "toolbarBorder": "#FF1E2226",
          "toolbarText": "#FF9BA5AE",
          "toolbarTextHover": "#FF8FC1FF",
          "accent": "#FF6CB6FF",
          "sidebarBg": "#FF262B30",
          "sidebarBorder": "#FF1E2226",
          "sidebarText": "#FF9BA5AE",
          "sidebarTextActive": "#FF6CB6FF",
          "sidebarHoverBg": "#FF333940",
          "statusBarBg": "#FF262B30",
          "statusBarText": "#FF7C868F",
          "panelBg": "#FF2F353B",
          "panelBorder": "#FF3C434A",
          "controlBg": "#FF333940",
          "controlBorder": "#FF3C434A",
          "editorBg": "#FF363B40",
          "text": "#FFC6CDD5",
          "textSecondary": "#FF9BA5AE",
          "heading": "#FFE7E9EB",
          "headingBorder": "#FF40464D",
          "link": "#FF6CB6FF",
          "rule": "#FF434A51",
          "inlineCodeText": "#FFE0A96D",
          "codeBg": "#FF2E3338",
          "codeBorder": "#FF40464D",
          "codeText": "#FFC6CDD5",
          "codeHeaderText": "#FF7C868F",
          "quoteText": "#FF9BA5AE",
          "quoteBorder": "#FF4A525A",
          "tableBorder": "#FF434A51",
          "tableHeaderBg": "#FF2E3338",
          "tableHeaderText": "#FFE7E9EB",
          "tableStripeBg": "#0DFFFFFF",
          "syntaxKeyword": "#FFD98EAF",
          "syntaxType": "#FFE0A96D",
          "syntaxString": "#FFA3C9A8",
          "syntaxNumber": "#FF92B6E8",
          "syntaxComment": "#FF7C868F",
          "syntaxFunction": "#FFC1A0E8",
          "syntaxOperator": "#FF8FC1FF",
          "syntaxPunctuation": "#FF9BA5AE",
          "syntaxVariable": "#FFC6CDD5",
          "syntaxBuiltin": "#FF8FC1FF"
        },
        "typography": { "baseFontSize": 16.5, "lineHeight": 1.8, "contentMaxWidth": 800 }
      },
      {
        "id": "vue-dark",
        "name": "Vue 暗色",
        "author": "内置",
        "isDark": true,
        "colors": {
          "windowBg": "#FF0B1A26",
          "toolbarBg": "#FF0E2130",
          "toolbarBorder": "#FF173045",
          "toolbarText": "#FF8FA6B8",
          "toolbarTextHover": "#FF63E2B7",
          "accent": "#FF63E2B7",
          "sidebarBg": "#FF0E2130",
          "sidebarBorder": "#FF173045",
          "sidebarText": "#FF8FA6B8",
          "sidebarTextActive": "#FF63E2B7",
          "sidebarHoverBg": "#FF14293A",
          "statusBarBg": "#FF0E2130",
          "statusBarText": "#FF6B8195",
          "panelBg": "#FF102434",
          "panelBorder": "#FF1D3A52",
          "controlBg": "#FF14293A",
          "controlBorder": "#FF1D3A52",
          "editorBg": "#FF0B1A26",
          "text": "#FFB9CBD9",
          "textSecondary": "#FF8FA6B8",
          "heading": "#FFE3EEF7",
          "headingBorder": "#FF173045",
          "link": "#FF63E2B7",
          "rule": "#FF173045",
          "inlineCodeText": "#FFF2C879",
          "codeBg": "#FF0E2130",
          "codeBorder": "#FF173045",
          "codeText": "#FFB9CBD9",
          "codeHeaderText": "#FF6B8195",
          "quoteText": "#FF8FA6B8",
          "quoteBorder": "#FF1D3A52",
          "tableBorder": "#FF173045",
          "tableHeaderBg": "#FF0E2130",
          "tableHeaderText": "#FFE3EEF7",
          "tableStripeBg": "#0DFFFFFF",
          "syntaxKeyword": "#FF63E2B7",
          "syntaxType": "#FFF2C879",
          "syntaxString": "#FFA5E6A5",
          "syntaxNumber": "#FF7DC4FF",
          "syntaxComment": "#FF6B8195",
          "syntaxFunction": "#FF9BB8FF",
          "syntaxOperator": "#FF7DC4FF",
          "syntaxPunctuation": "#FF8FA6B8",
          "syntaxVariable": "#FFB9CBD9",
          "syntaxBuiltin": "#FF7DC4FF"
        },
        "typography": { "baseFontSize": 16, "lineHeight": 1.8, "contentMaxWidth": 800 }
      },
      {
        "id": "dracula",
        "name": "Dracula 紫夜",
        "author": "内置",
        "isDark": true,
        "colors": {
          "windowBg": "#FF282A36",
          "toolbarBg": "#FF21222C",
          "toolbarBorder": "#FF191A21",
          "toolbarText": "#FF9AA0B5",
          "toolbarTextHover": "#FFBD93F9",
          "accent": "#FFBD93F9",
          "sidebarBg": "#FF21222C",
          "sidebarBorder": "#FF191A21",
          "sidebarText": "#FF9AA0B5",
          "sidebarTextActive": "#FFBD93F9",
          "sidebarHoverBg": "#FF2E3140",
          "statusBarBg": "#FF21222C",
          "statusBarText": "#FF6272A4",
          "panelBg": "#FF2B2E3B",
          "panelBorder": "#FF3A3D4D",
          "controlBg": "#FF2E3140",
          "controlBorder": "#FF3A3D4D",
          "editorBg": "#FF282A36",
          "text": "#FFF8F8F2",
          "textSecondary": "#FF9AA0B5",
          "heading": "#FFF8F8F2",
          "headingBorder": "#FF3A3D4D",
          "link": "#FF8BE9FD",
          "rule": "#FF3A3D4D",
          "inlineCodeText": "#FFFF79C6",
          "codeBg": "#FF21222C",
          "codeBorder": "#FF3A3D4D",
          "codeText": "#FFF8F8F2",
          "codeHeaderText": "#FF6272A4",
          "quoteText": "#FF9AA0B5",
          "quoteBorder": "#FF6272A4",
          "tableBorder": "#FF3A3D4D",
          "tableHeaderBg": "#FF21222C",
          "tableHeaderText": "#FFF8F8F2",
          "tableStripeBg": "#0DFFFFFF",
          "syntaxKeyword": "#FFFF79C6",
          "syntaxType": "#FF8BE9FD",
          "syntaxString": "#FFF1FA8C",
          "syntaxNumber": "#FFBD93F9",
          "syntaxComment": "#FF6272A4",
          "syntaxFunction": "#FF50FA7B",
          "syntaxOperator": "#FFFF79C6",
          "syntaxPunctuation": "#FFF8F8F2",
          "syntaxVariable": "#FFF8F8F2",
          "syntaxBuiltin": "#FF8BE9FD"
        },
        "typography": { "baseFontSize": 16, "lineHeight": 1.78, "contentMaxWidth": 800 }
      }
    ]
    """;
}
